version: "3.9"

services:
  wordpress:
    image: vangoda/wordpress-dev:1.2
    container_name: test.local
    volumes:
      - test:/var/www/html
      - ./shared:/var/www/html/shared
      # Keep vscode remote server in volume to avoid reinstalling
      - vscode:/home/www-data/
      - ./config-custom/nginx.conf:/etc/nginx/nginx.conf
      - ./config-custom/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config-custom/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      - VIRTUAL_HOST=test.local
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER{WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD={WORDPRESS_DB_PASSWORD}
    networks:
      - nginx-proxy

  db:
    image: mariadb
    # command: --max_allowed_packet=67108864
    volumes:
      - db:/var/lib/mysql
      - ./current.sql:/current.sql
      - ./config-custom/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MARIADB_ROOT_PASSWORD: {MARIADB_ROOT_PASSWORD}
    networks:
      - nginx-proxy

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    networks:
      - nginx-proxy
    environment:
      - PMA_ABSOLUTE_URI=pma.localhost
      - VIRTUAL_HOST=pma.localhost
      - UPLOAD_LIMIT=100M
      - HIDE_PHP_VERSION=true
      - proxy_read_timeout=1500

volumes:
  h2oclub:
  vscode:
  db:

networks:
  nginx-proxy:
    external: true